### ISSUE TITLE
events file still exists in Files app after updating to 3.0.10

### ISSUE THREAD

**Issue by ashender** [castle/castle-ios#115] opened 2024-07-17 02:00 UTC
while browsing app documents in Files.app I still can see castle/events file. after updating castle sdk to 3.0.10 this file stopped being updated, but was not moved. Looks like there is a migration code in the Castle repo but it is not being run in our case.

**Comment by aalekz** [comment] 2024-07-25 09:38
Hi @ashender,

Thanks for reporting the issue. I've investigated the issue and as far as I can see the migration code is working as expected, at least in our test cases. I've re-worked the migration code and made sure that the old storage directory is excluded from any backups thinking that might be the reason it still exists.

Am I understanding it correctly that you can reproduce this behavior on your device? I have opened a new pull request (https://github.com/castle/castle-ios/pull/117) and was wondering if you could try out the new version and see if the error persists?

Thanks,
Alex

**Comment by ashender** [comment] 2024-07-26 02:27
Hi @aalekz , 
looks like eventsQueue is initialised [here](https://github.com/castle/castle-ios/blob/9c964a68fb9f6a93c458aabf85df586ac60562bb/Castle/Public/Castle.m#L346)

migration code runs only if this queue is nil in the storageQueue, but since it is never nil in my case it is never run

**Comment by aalekz** [comment] 2024-07-26 11:06
Hi @ashender,

I've updated the code to run the migration when the queue is persisted and this solves the issue according to my tests. Would it be possible for you to verify the fix on your end as well before I create a new release?

Thanks,
Alex

**Comment by ashender** [comment] 2024-07-30 05:57
Hi @aalekz , can confirm that running with mentioned above branch issue is resolved and castle folder is removed. please lmk when next release will be out

**Comment by aalekz** [comment] 2024-08-01 13:30
Version 3.0.11 is now released, closing the issue. I will also take a look at providing static versions of the internal libraries in the next release.

Thank you for reporting this issue @ashender and please let us know if there is anything else in the future.

**Closed by aalekz** 2024-08-01 13:30 UTC
